### ISSUE TITLE
Is there a presentation for the project?

### ISSUE THREAD

**Issue by hdamron17** [jacky841102/HD_map_updating#5]
Hi, I am working with Dr. Mertz on an extension of the project. Are there any papers or presentation slides which accompany this project? These would be very helpful in understanding how the code is working.

Also, can you point me to where the sign_detection module creates a ".npz" to be used in the 3D_projection module? The only output I see is the image with bounding boxes drawn on.

**Comment by jacky841102** [comment]
Hi, you can find the presentation slides [here](https://drive.google.com/file/d/1O8zqemrsokpryy7cVcxBOXNcY2zAmRUh/view).

Regarding the ".npz" file from sign_detection, it seems we don't integrate the code into the repo yet, or I miss it. @yi-ting-lin could you resolve the issue?

**Comment by hdamron17** [comment]
Thanks!

**Comment by yi-ting-lin** [comment]
Hi,
This part has not been pushed yet and I will do it later this week.
For reference to .npy, you may check out the [link](https://drive.google.com/file/d/1k5DZqT1CnZqULno_cTyWIRP36APoyRZB/view?usp=sharing) to get access to the .npy we currently use.

**Comment by jacky841102** [comment]
Refer to #6
